//
//  Bundle+Module.swift
//  SwiftUIUtilities
//
//  Created by Package on 13/01/26.
//

import Foundation
import class Foundation.Bundle

/// Private class used to locate the resource bundle
private class BundleToken {}

extension Foundation.Bundle {
    /// Returns the resource bundle associated with the current Swift module.
    /// 
    /// This works whether Bundle.module is auto-generated by SPM or not.
    static let swiftUIUtilitiesModule: Bundle = {
        // First, try to use the auto-generated Bundle.module if available
        #if SWIFT_PACKAGE
        // This will use SPM's auto-generated Bundle.module
        return Bundle.module
        #else
        // Fallback for non-SPM scenarios
        let bundleName = "SwiftUIUtilities_SwiftUIUtilities"
        
        let candidates = [
            // Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,
            
            // Bundle should be present here when the package is linked into a framework.
            Bundle(for: BundleToken.self).resourceURL,
            
            // For command-line tools.
            Bundle.main.bundleURL,
        ]
        
        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }
        
        // If we can't find the resource bundle, return the framework bundle
        return Bundle(for: BundleToken.self)
        #endif
    }()
}
